s: linux
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - main
script:
  - hexo c
  - hexo g
deploy:
  provider: pages
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: main
  local-dir: public
