sudo: false
language: node_js
node_js:
  - v17.7.1
cache: npm
branches:
  only:
    - main 
script:
  - ls -a
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
