language: node_js
node_js:
  - 15
cache: npm
branches:
  only:
    - main
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
