s: linux
language: node_js
node_js:
  - 15
cache:
  directories:
    - node_modules
branches:
  only:
    - main
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: main
  local-dir: public
