os: linue
sudo: false
language: node_js
node_js:
  - 15
cache: npm
branches:
  only:
    - main
cache:
  directories:
    - node_modules
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
